# Site settings
title: Dev & Community
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dev & Community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devcommunitycast.com.br/" # the base hostname & protocol for your site

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
excerpt_separator: <!--preview-->

disqus: true
disqus_shortname: 'test-henrique'

members:
  - name: Neto Marin
    url: https://twitter.com/netomarin
    image: http://sp.devfest.com.br/2014/img/speakers/neto_marin.png
    description: Developer Advocate for Android, Cloud and Social at Google, with focus on LatAm, but first at all, a passionate and dedicated dad and husband!
  - name: Alê Borba
    url: https://twitter.com/ale_borba
    image: http://sp.devfest.com.br/2014/img/speakers/ale_borba.jpg
    description: Community Manager focus on Developers and Technical communities. Working hard to grow the communities that we are envolved in.