# Site settings
title: Dev & Community
email: your-email@domain.com
description: Dev & Community.
baseurl: "/devcommunity-proposal" # the subpath of your site, e.g. /blog/
url: "http://devcommunitycast.com.br/" # the base hostname & protocol for your site

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
excerpt_separator: <!--preview-->

disqus: true
disqus_shortname: 'test-henrique'

members:
  - name: Neto Marin
    url: https://twitter.com/netomarin
    image: http://sp.devfest.com.br/2014/img/speakers/neto_marin.png
    description: Developer Advocate for Android, Cloud and Social at Google, with focus on LatAm, but first at all, a passionate and dedicated dad and husband!
  - name: Alê Borba
    url: https://twitter.com/ale_borba
    image: http://sp.devfest.com.br/2014/img/speakers/ale_borba.jpg
    description: Community Manager focus on Developers and Technical communities. Working hard to grow the communities that we are envolved in.

feeds:
  - url: "http://devcommunitycast.com.br/feed/podcast/"
    description: via RSS
    title: Assinar via RSS
    icon: rss_feed
  - url: "https://itunes.apple.com/br/podcast/dev-community-cast/id1101607027?l=en&mt=2&ls=1"
    description: no Itunes
    title: Assinar no Itunes
    icon: wifi_tethering
  - url: "http://subscribeonandroid.com/devcommunitycast.com.br/feed/podcast/"
    description: no Android
    title: Assinar no Android
    icon: android
  - url: "http://subscribebyemail.com/devcommunitycast.com.br/feed/podcast/"
    description: no Email
    title: Assinar via Email
    icon: email