# Site settings
title: Dev & Community
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dev & Community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devcommunitycast.com.br/" # the base hostname & protocol for your site

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
excerpt_separator: <!--preview-->

disqus: true
disqus_shortname: 'test-henrique'

# Build settings
markdown: kramdown
